// Generated by CoffeeScript 1.6.3
(function() {
  var slider, tabs;

  slider = function(slider, wrapper) {
    var $selectors, $slider, $slides, $wrapper, changeSlide, current, options, updateSelector;
    $slider = $(slider);
    $wrapper = $(wrapper);
    $slides = $('.slide', $slider);
    $selectors = $('.selector a', $slider);
    current = 0;
    options = {
      width: 1000,
      delay: 400
    };
    updateSelector = function() {
      $selectors.removeClass('active');
      return $selectors.eq(current).addClass('active');
    };
    changeSlide = function(i) {
      var $slide;
      $slide = $slides.eq(current);
      if (i > current) {
        if ($slide.index() >= $slides.length - 1) {
          return false;
        }
        $slide.animate({
          left: -options.width
        }, options.delay, function() {
          $slide.hide();
          return $slide.next().show().css({
            left: options.width
          }).animate({
            left: 0
          }, options.delay);
        });
        ++current;
        updateSelector();
      } else if (i < current) {
        if (current <= 0) {
          return false;
        }
        $slide.animate({
          left: options.width
        }, options.delay, function() {
          $slide.hide();
          return $slide.prev().show().css({
            left: -options.width
          }).animate({
            left: 0
          }, options.delay);
        });
        --current;
        updateSelector();
      } else {
        return false;
      }
      if (i !== current) {
        return changeSlide(i);
      }
    };
    $('.next', $slider).click(function(e) {
      changeSlide(current + 1);
      return false;
    });
    $('.back', $slider).click(function(e) {
      changeSlide(current - 1);
      return false;
    });
    return $selectors.click(function() {
      return changeSlide($(this).data('slide'));
    });
  };

  tabs = function(wrapper) {
    var $nav, $tabs;
    $tabs = $('.tab', $(wrapper));
    $nav = $('.nav li', $(wrapper));
    return $nav.click(function() {
      var $this;
      $this = $(this);
      $nav.removeClass('active');
      $this.addClass('active');
      $tabs.hide();
      return $tabs.eq($this.data('tab')).show();
    });
  };

  jQuery(document).ready(function($) {
    slider('.slider', '.slide-wrapper');
    return tabs('.tabs');
  });

}).call(this);
